### PR TITLE
Remove multiple_of

### PR DESCRIPTION
**Pull request by YingboMa**
Fix https://github.com/shashi/SymbolicUtils.jl/issues/23

### CODE REVIEW

**Comment by MasonProtter** [comment]
I disagree with removing these identities. I'd say that it's the identities that are correct and the floating point math that fails to live up to the identities. If we can do better than floating point math, then I think we should if possible.

**Comment by YingboMa** [comment]
Giving suboptimal results is far better than wrong results.

**Comment by ChrisRackauckas** [comment]
Respecting math and respecting floating point math are two different things. IIRC the plan is to have different rule sets, and having math simplify vs floating point math simplify would be a good distinction, since different applications require different choices.

**Comment by YingboMa** [comment]
We could define our own lazy `pi`, but that's pretty inconvenient to use.

**Comment by YingboMa** [comment]
> I'd say that it's the identities that are correct and the floating point math that fails to live up to the identities.

I mean, mathematically
```julia
multiple_of(x, tol=1e-10) = y -> (y isa Number) && abs(y % x) < 1e-10
```
is wrong.

**Comment by MasonProtter** [comment]
That said, your example in https://github.com/shashi/SymbolicUtils.jl/issues/23#issue-606820738 is fairly convincing that things can go wrong if the integer is sufficiently big. This is unfortunate because `eps(2pi) ~ 9e-16` whereas `1/typemax(Int) ~ 1e-19` so there's always 64 bit integers that are big enough to cause problems.

**Comment by MasonProtter** [comment]
However, consider the fact that 
```julia
julia> eps(1e16)
2.0
```
so any result you get from `tan(x)` where `x ~ 1e16` is meaningless anyways:
```julia
julia> tan(1e16 + nextfloat(1e16))
4.524145195044381

julia> tan(1e16)
-1.2451734357184066
```

**Comment by YingboMa** [comment]
I doubt that's any better
```julia
julia> tan(0)
0.0

julia> tan(0 + (2pi - 1e-16) * 1<<63)
0.2762097146903194
```

**Comment by MasonProtter** [comment]
Yingbo, trigonometric functions applied to float64s that are that big are utterly meaningless. There is no "right answer" to `tan(0 + (2pi - 1e-16) * 1<<63)` other than promoting everything to BigFloat.

**Comment by YingboMa** [comment]
I very much oppose defining non-equivalence relations on floating-point numbers in a symbolic library. If anything, we should define our own lazy transcendental numbers.

**Comment by MasonProtter** [comment]
> If anything, we should define our own lazy transcendental numbers.

Sure, that'd be great. But it's also useful to be able to do simplifications on generic julia code that isn't written using arbitrary precision or transcendental numbers.

**Comment by MasonProtter** [comment]
```julia
julia> (1e16 + 1) - 1e16
0.0
```
I don't think this is a convincing argument for removing our `+` simplification rules.

**Comment by YingboMa** [comment]
There is a reason that
```julia
julia> tan(2pi)
-2.4492935982947064e-16
```
is not zero. Because `2pi` is a floating-point. We cannot just treat any floating point that's close enough to 2pi as 2pi.

**Comment by YingboMa** [comment]
I think instead, we should add rules on `sinpi/cospi`, they are designed to do that
```julia
julia> sin(2pi)
-2.4492935982947064e-16

julia> sinpi(2)
0.0
```

**Comment by YingboMa** [comment]
> I don't think this is a convincing argument for removing our + simplification rules.

I think they are quite fundamentally different. In the case of 2pi, we don't have the information to determine that

```julia
julia> using SymbolicUtils

julia> @vars x::Real
(x,)

julia> x - x
((-1 * x) + x)

julia> x + 2pi
(6.283185307179586 + x)
```

**Comment by MasonProtter** [comment]
In what way are they different? 
```julia
julia> t = term(-, term(+, 1e16, 1.0), 1e16); showraw(t)
((1.0e16 + 1.0) - 1.0e16)

julia> @rule(~x + ~y - ~x => ~y)(t)
1.0

julia> 1e16 + 1 - 1e16
0.0
```
If a user puts something meaningless into a symbolic library and get's a different answer than when they put that meaningless input into julia, that's their fault, not ours.

**Comment by YingboMa** [comment]
You know mathematically that
```julia
julia> using SymbolicUtils

julia> @vars x::Real
(x,)

julia> x - x
((-1 * x) + x)
```
is zero, but how do you know
```julia
julia> x + 2pi
(6.283185307179586 + x)
```
has two pi?

**Comment by MasonProtter** [comment]
It's floating point arithmetic. You don't know anything. Everything has implicit errorbars. 

In particular you do **not** know that `x + y - x == y`.

**Comment by YingboMa** [comment]
I know I can do `x + y - x == y` because I have the expression, but I don't know `6.283185307179586` is 2pi.

**Comment by MasonProtter** [comment]
```julia
julia> let x = 1e16, y = 1
           @assert x == x
           @assert x === x
           x + y - x == y
       end
false
```

If a user is not comfortable with accumulating error, they should not use types which accumulate error.

**Comment by YingboMa** [comment]
I am not talking about accumulating errors at all. It's quite obvious that
```julia
julia> 6 + sum(((i, x),)->x/10^i, enumerate(reverse(digits(283185307179586))))
6.283185307179586
```
is not 2pi.

**Comment by shashi** [comment]
>  I'd say that it's the identities that are correct and the floating point math that fails to live up to the identities.

This is controversial enough that we shouldn't have it in this package. Also floating point errors are best left as they are rather than do this type of rounding which complicates analysis.

These rules would only make sense if we used a symbolic pi, I'm open to adding that, and other constants that people may want to simplify.

**Comment by YingboMa** [comment]
I don't get what's the problem.

> I know I can do x + y - x == y because I have the expression, but I don't know 6.283185307179586 is 2pi.

I didn't say anything about the floating-point error. You can do that simplification because you know the expression.

**Comment by MasonProtter** [comment]
Alright, let's remove this.

If we make an IRTools or Cassette pass, we can use it to replace instances of `pi` with a symbolic pi and then we can resolve these things exactly.

**Comment by ChrisRackauckas** [comment]
I know @shashi hates it but this is why `Constant` exists: at some point I think you do need to take control of "symbolic constants" and force them to not do the Julia thing.

**Comment by shashi** [comment]
> I know @shashi hates it but this is why Constant exists: at some point I think you do need to take control of "symbolic constants" and force them to not do the Julia thing.

Well the way to do this kind of constant is probably, `pi = Variable{Const{:pi}}(:pi)` and export that, and make it be a symbolic citizen. Using `Const` here to separate `@vars pi` in user code.

As far as I can tell the purpuse of MTK Constant is it lets you view julia numbers as subtype of Expression. Which is different.

**Comment by MasonProtter** [comment]
Is there a reason that the lines here are commented out instead of deleted?

**Pull request merged**
